# installed by github.com/mediacloud/system-dev-ops/monitoring/nginx-agent

# from https://www.tecmint.com/amplify-nginx-monitoring-tool/
server {
  listen      127.0.0.1:80;
  server_name 127.0.0.1;

  location /nginx_status {
 	stub_status;
 	allow 127.0.0.1;	#only allow requests from localhost
 	deny all;		#deny all other hosts	
  }
}
