{
 "title": "Elasticsearch Graphs",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "realm",
    "query": "prod, hist-prod,rss-prod,csv-prod,staging, pbudne, pgulley,new"
   }
  ]
 },
 "panels": [
  {
   "title": "ES server CPU%",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "stats.gauges.mc.$realm.story-indexer.elastic-stats.cat.nodes.cpu.*"
    }
   ]
  },
  {
   "title": "ES server 5 minute load average",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "stats.gauges.mc.$realm.story-indexer.elastic-stats.cat.nodes.load_5m.*"
    }
   ]
  },
  {
   "title": "mc_search documents",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "alias(sumSeries(stats.gauges.mc.$realm.story-indexer.elastic-stats.indices.indices.primaries.docs.count.name_mc_search*), 'es_documents')"
    }
   ]
  },
  {
   "title": "mc_search size in bytes (TB = 1e12)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "target": "sumSeries(stats.gauges.mc.$realm.story-indexer.elastic-stats.indices.indices.primaries.store.size_in_bytes.name_mc_search*)"
    }
   ]
  },
  {
   "title": "total documents",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "stats.gauges.mc.$realm.story-indexer.elastic-stats.indices.all.primaries.docs.count"
    }
   ]
  },
  {
   "title": "all primary index bytes TB = 1e12)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "target": "stats.gauges.mc.$realm.story-indexer.elastic-stats.indices.all.primaries.store.size_in_bytes"
    }
   ]
  },
  {
   "title": "Shard Status",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "stats.gauges.mc.$realm.story-indexer.elastic-stats.cluster.health.shards.*"
    }
   ]
  },
  {
   "title": "index health",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "stats.gauges.mc.$realm.story-indexer.elastic-stats.indices.health.*"
    }
   ]
  },
  {
   "title": "Document Import rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "nonNegativeDerivative(stats.gauges.mc.$realm.story-indexer.elastic-stats.indices.indices.primaries.docs.count.name_mc_search-*)"
    }
   ]
  },
  {
   "title": "ES thread pool queue length",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "nonNegativeDerivative(stats.gauges.mc.$realm.story-indexer.elastic-stats.node.thread_pool.queue.*.*)"
    }
   ]
  },
  {
   "title": "mean indexing latency",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "target": "divideSeries(nonNegativeDerivative(stats.gauges.mc.$realm.story-indexer.elastic-stats.indices.all.primaries.indexing.index_time_in_millis), #A)",
     "targetFull": "divideSeries(nonNegativeDerivative(stats.gauges.mc.$realm.story-indexer.elastic-stats.indices.all.primaries.indexing.index_time_in_millis), nonNegativeDerivative(stats.gauges.mc.$realm.story-indexer.elastic-stats.indices.all.primaries.indexing.index_total))"
    }
   ]
  },
  {
   "title": "Deleted documents",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 40 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "stats.gauges.mc.$realm.story-indexer.elastic-stats.indices.all.primaries.docs.deleted"
    }
   ]
  },
  {
   "title": "All primaries \"*_count\"  per minute",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 48 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "target": "nonNegativeDerivative(stats.gauges.mc.$realm.story-indexer.elastic-stats.indices.all.primaries.*.*_total)"
    }
   ]
  },
  {
   "title": "mean query latency",
   "type": "graph",
   "description": "NOTE: story indexing does a (quick) query before each story is added, which dilutes values in this graph!\n",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 48 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "target": "divideSeries(nonNegativeDerivative(stats.gauges.mc.$realm.story-indexer.elastic-stats.indices.all.primaries.search.query_time_in_millis), #A)",
     "targetFull": "divideSeries(nonNegativeDerivative(stats.gauges.mc.$realm.story-indexer.elastic-stats.indices.all.primaries.search.query_time_in_millis), nonNegativeDerivative(stats.gauges.mc.$realm.story-indexer.elastic-stats.indices.all.primaries.search.query_total))"
    }
   ]
  },
  {
   "title": "JVM GC  time (ms)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 56 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "target": "nonNegativeDerivative(stats.gauges.mc.$realm.story-indexer.elastic-stats.node.jvm.gc.collection_millis.*)"
    }
   ]
  },
  {
   "title": "JVM Heap percent used",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 56 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "target": "stats.gauges.mc.$realm.story-indexer.elastic-stats.node.jvm.mem.heap_used_percent.*"
    }
   ]
  },
  {
   "title": "all indices times in millis",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 64 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "target": "alias(sumSeries(nonNegativeDerivative(stats.gauges.mc.$realm.story-indexer.elastic-stats.indices.indices.primaries.bulk.*time_in_millis.name_mc*)), 'bulk')"
    },
    {
     "target": "alias(sumSeries(nonNegativeDerivative(stats.gauges.mc.$realm.story-indexer.elastic-stats.indices.indices.primaries.recovery.*time_in_millis.name_mc*)), 'recovery')"
    },
    {
     "target": "alias(sumSeries(nonNegativeDerivative(stats.gauges.mc.$realm.story-indexer.elastic-stats.indices.indices.primaries.merges.*time_in_millis.name_mc*)), 'merges')"
    },
    {
     "target": "alias(sumSeries(nonNegativeDerivative(stats.gauges.mc.$realm.story-indexer.elastic-stats.indices.indices.primaries.warmer.*time_in_millis.name_mc*)), 'warmer')"
    },
    {
     "target": "alias(sumSeries(nonNegativeDerivative(stats.gauges.mc.$realm.story-indexer.elastic-stats.indices.indices.primaries.indexing.*time_in_millis.name_mc*)), 'indexing')"
    },
    {
     "target": "alias(sumSeries(nonNegativeDerivative(stats.gauges.mc.$realm.story-indexer.elastic-stats.indices.indices.primaries.search.*time_in_millis.name_mc*)), 'search')"
    },
    {
     "target": "alias(sumSeries(nonNegativeDerivative(stats.gauges.mc.$realm.story-indexer.elastic-stats.indices.indices.primaries.refresh.*time_in_millis.name_mc*)), 'refresh')"
    },
    {
     "target": "alias(sumSeries(nonNegativeDerivative(stats.gauges.mc.$realm.story-indexer.elastic-stats.indices.indices.primaries.flush.*time_in_millis.name_mc*)), 'flush')"
    },
    {
     "target": "alias(sumSeries(nonNegativeDerivative(stats.gauges.mc.$realm.story-indexer.elastic-stats.indices.indices.primaries.get.*time_in_millis.name_mc*)), 'get')"
    }
   ]
  },
  {
   "title": "all indices avg time in millis",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 64 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "target": "nonNegativeDerivative(stats.gauges.mc.$realm.story-indexer.elastic-stats.indices.all.primaries.*.*_in_millis)"
    }
   ]
  },
  {
   "title": "http client connections (stacked)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 72 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "stats.gauges.mc.$realm.story-indexer.elastic-stats.node.http.client_count.*"
    }
   ]
  },
  {
   "title": "ES Circuit Breakers",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 72 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "alias(sumSeries(nonNegativeDerivative(stats.gauges.mc.$realm.story-indexer.elastic-stats.node.breakers.tripped.name_parent.*)), 'parent')"
    },
    {
     "target": "alias(sumSeries(nonNegativeDerivative(stats.gauges.mc.$realm.story-indexer.elastic-stats.node.breakers.tripped.name_fielddata.*)), 'fielddata')"
    },
    {
     "target": "alias(sumSeries(nonNegativeDerivative(stats.gauges.mc.$realm.story-indexer.elastic-stats.node.breakers.tripped.name_request.*)), 'request')"
    },
    {
     "target": "alias(sumSeries(nonNegativeDerivative(stats.gauges.mc.$realm.story-indexer.elastic-stats.node.breakers.tripped.name_inflight_requests.*)), 'inflight')"
    }
   ]
  },
  {
   "title": "MC Provider Query Rates",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 80 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "stats.counters.mc.$realm.*.provider.es.query.*.rate"
    }
   ]
  },
  {
   "title": "ES server data partition percent used",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 80 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "target": "stats.gauges.mc.systems.disk.pct.es*.data"
    }
   ]
  },
  {
   "title": "Time since last successful snapshot",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 88 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "target": "stats.gauges.mc.$realm.story-indexer.elastic-stats.snapshot.time_since_last_start.state_success"
    }
   ]
  }
 ]
}