{
 "title": "Paige Sandbox",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "fetcher fetched stories",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "stats.counters.mc.pgulley.story-indexer.fetcher.fetched-stories.*.count"
    }
   ]
  },
  {
   "title": "Oversized Story Count",
   "type": "graph",
   "gridPos": { "h": 10, "w": 11, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "stats.gauges.mc.pgulley.story-indexer.fetcher.oversize-stories.*"
    }
   ]
  },
  {
   "title": "Parser methods",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "stats.counters.mc.pgulley.story-indexer.parser.parsed-stories.*.count"
    }
   ]
  },
  {
   "title": "fetcher queued stories",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "stats.gauges.mc.pgulley.story-indexer.fetcher.queued-stories.*"
    }
   ]
  },
  {
   "title": "Importer",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "stats.counters.mc.pgulley.story-indexer.importer.imported-stories.*.count"
    }
   ]
  }
 ]
}