{
 "title": "Phil's Sandbox",
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "realm",
    "query": "prod, hist-prod,rss-prod,csv-prod,staging, pbudne, pgulley,arch-prod"
   }
  ]
 },
 "panels": [
  {
   "title": "Fetch time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "target": "stats.timers.mc.$realm.story-indexer.fetcher.fetch.mean"
    },
    {
     "target": "stats.timers.mc.$realm.story-indexer.fetcher.fetch.median"
    }
   ]
  },
  {
   "title": "Importer statuses as percentages",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "asPercent(stats.counters.mc.$realm.story-indexer.importer.stories.*.count)"
    }
   ]
  },
  {
   "title": "Q fetcher requests",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "stats.gauges.mc.$realm.story-indexer.fetcher.requests.*"
    },
    {
     "target": "stats.gauges.mc.$realm.story-indexer.fetcher.prefetch"
    }
   ]
  },
  {
   "title": "fetcher queue derivative",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "derivative(sumSeries(stats.gauges.mc.$realm.story-indexer.rabbitmq-stats.queues.ready.name_fetcher-*))"
    }
   ]
  },
  {
   "title": "q fetch get_delay time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "target": "stats.timers.mc.$realm.story-indexer.fetcher.get_delay.upper"
    },
    {
     "target": "stats.timers.mc.$realm.story-indexer.fetcher.get_delay.lower"
    },
    {
     "target": "stats.timers.mc.$realm.story-indexer.fetcher.get_delay.mean"
    }
   ]
  },
  {
   "title": "Qfetch slots",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "stats.gauges.mc.$realm.story-indexer.fetcher.slots.*"
    }
   ]
  },
  {
   "title": "q fetch finish time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "target": "stats.timers.mc.$realm.story-indexer.fetcher.finish.upper"
    },
    {
     "target": "stats.timers.mc.$realm.story-indexer.fetcher.finish.lower"
    },
    {
     "target": "stats.timers.mc.$realm.story-indexer.fetcher.finish.mean"
    }
   ]
  },
  {
   "title": "parser extracted pub date",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "target": "stats.timers.mc.$realm.story-indexer.parser.extracted-pub-date.upper_90"
    }
   ]
  },
  {
   "title": "page text fetch time seen by importer",
   "type": "graph",
   "description": "gives an idea how \"far behind\" the importer is; for historical data it will be YEARS!",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "yaxes": [
    { "format": "dateTimeAsIso" }
   ],
   "targets": [
    {
     "target": "stats.timers.mc.$realm.story-indexer.importer.fetch-ts.lower"
    },
    {
     "target": "stats.timers.mc.$realm.story-indexer.importer.fetch-ts.upper"
    }
   ]
  },
  {
   "title": "fetch time spread seen by importer",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 40 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "target": "diffSeries(stats.timers.mc.$realm.story-indexer.importer.fetch-ts.upper, #D)",
     "targetFull": "diffSeries(stats.timers.mc.$realm.story-indexer.importer.fetch-ts.upper, stats.timers.mc.$realm.story-indexer.importer.fetch-ts.lower)"
    }
   ]
  }
 ]
}