{
 "title": "rss-fetcher alerts",
 "time": { "from": "now-24h", "to": "now" },
 "panels": [
  {
   "title": "stories processed per hour",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "summarize(stats.counters.mc.prod.rss-fetcher.fetcher.stories.stat_ok.count, '1h', 'sum', false)"
    }
   ]
  },
  {
   "title": "rss stories output",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "summarize(stats.counters.mc.prod.rss-fetcher.gen_rss.stories.status_added.count, '1h', 'sum', false)"
    }
   ]
  },
  {
   "title": "Top domain stories/day (3 day average)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "stats.gauges.mc.prod.rss-fetcher.rss-fetcher-stats.stories.top-domain.avg.days_3"
    }
   ]
  }
 ]
}