{
 "title": "rss-fetcher",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "realm", "query": "prod,staging,pbudne" }
  ]
 },
 "panels": [
  {
   "title": "feed status",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "stats.gauges.mc.$realm.rss-fetcher.fetcher.db.ready"
    },
    {
     "target": "stats.gauges.mc.$realm.rss-fetcher.fetcher.db.running"
    },
    {
     "target": "stats.gauges.mc.$realm.rss-fetcher.fetcher.on_hand"
    },
    {
     "target": "stats.gauges.mc.$realm.rss-fetcher.fetcher.hunter.blocked"
    }
   ]
  },
  {
   "title": "delay from ready to start",
   "type": "graph",
   "description": "max time from next_fetch_attempt until start of fetch\n",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "target": "stats.timers.mc.$realm.rss-fetcher.fetcher.start_delay.upper"
    },
    {
     "target": "stats.timers.mc.$realm.rss-fetcher.fetcher.start_delay.lower"
    }
   ]
  },
  {
   "title": "feeds processed / second",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "stats.counters.mc.$realm.rss-fetcher.fetcher.feeds.*.rate"
    }
   ]
  },
  {
   "title": "max fetch and processing time",
   "type": "graph",
   "description": "maximum time to fetch, parse, and store\n",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "target": "stats.timers.mc.$realm.rss-fetcher.fetcher.total.*.upper"
    }
   ]
  },
  {
   "title": "stories processed / second",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "stats.counters.mc.$realm.rss-fetcher.fetcher.stories.*.rate"
    }
   ]
  },
  {
   "title": "RSS stories output",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 20 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "stats.counters.mc.$realm.rss-fetcher.gen_rss.stories.*.count"
    }
   ]
  },
  {
   "title": "worker processes",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 29 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "stats.gauges.mc.$realm.rss-fetcher.fetcher.workers.*"
    }
   ]
  },
  {
   "title": "auto-adjust rate (per second)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 29 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "stats.counters.mc.$realm.rss-fetcher.fetcher.adjust.*.rate"
    }
   ]
  },
  {
   "title": "hunter rates (per second)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 37 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "stats.counters.mc.$realm.rss-fetcher.fetcher.hunter.*.rate"
    }
   ]
  },
  {
   "title": "Active Feeds",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 37 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "stats.gauges.mc.$realm.rss-fetcher.rss-fetcher-stats.feeds.recent.hours_*.status_*"
    }
   ]
  },
  {
   "title": "Sources with Active Feeds",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 45 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "stats.gauges.mc.$realm.rss-fetcher.rss-fetcher-stats.sources.recent.hours_*.status_*"
    }
   ]
  }
 ]
}