{
 "title": "Server stats",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "5m",
 "panels": [
  {
   "title": "CPU percent",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "target": "stats.gauges.mc.systems.cpu.pct.*"
    }
   ]
  },
  {
   "title": "15 minute load average",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "stats.gauges.mc.systems.load.15.*"
    }
   ]
  },
  {
   "title": "Memory percent",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "target": "stats.gauges.mc.systems.vm.pct.*"
    }
   ]
  },
  {
   "title": "Swap percent",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "target": "stats.gauges.mc.systems.swap.pct.*"
    }
   ]
  },
  {
   "title": "Disk percent",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "target": "stats.gauges.mc.systems.disk.pct.*.*"
    }
   ]
  },
  {
   "title": "iowait time (sum of ms for all CPUs)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 18 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "target": "scale(nonNegativeDerivative(stats.gauges.mc.systems.cpu.state.*.iowait), 10)"
    }
   ]
  },
  {
   "title": "Read IOPs per minute",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "rpm" }
   ],
   "targets": [
    {
     "target": "nonNegativeDerivative(stats.gauges.mc.systems.disk.stats.count.read.*.*data)"
    }
   ]
  },
  {
   "title": "Write IOPs per minute",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 27 },
   "yaxes": [
    { "format": "wpm" }
   ],
   "targets": [
    {
     "target": "nonNegativeDerivative(stats.gauges.mc.systems.disk.stats.count.write.*.*data)"
    }
   ]
  },
  {
   "title": "Read time",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 38 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "target": "nonNegativeDerivative(stats.gauges.mc.systems.disk.stats.time.read.*.*data)"
    }
   ]
  },
  {
   "title": "Write time",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 38 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "target": "nonNegativeDerivative(stats.gauges.mc.systems.disk.stats.time.write.*.*data)"
    }
   ]
  },
  {
   "title": "Network Packets In/Minute",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 49 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "target": "nonNegativeDerivative(stats.gauges.mc.systems.net.pkts.rx.ok.*.*)"
    }
   ]
  },
  {
   "title": "Network Packets Out/Minute",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 49 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "target": "nonNegativeDerivative(stats.gauges.mc.systems.net.pkts.tx.ok.*.*)"
    }
   ]
  },
  {
   "title": "Network Bytes In/Minute",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 60 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "target": "nonNegativeDerivative(stats.gauges.mc.systems.net.bytes.rx.*.*)"
    }
   ]
  },
  {
   "title": "Network Bytes Out/Minute",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 60 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "target": "nonNegativeDerivative(stats.gauges.mc.systems.net.bytes.tx.*.*)"
    }
   ]
  }
 ]
}