{
 "title": "Staging Dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Fetcher.FetchedStories",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "stats.counters.mc.staging.story-indexer.fetcher.fetched-stories.*.count"
    }
   ]
  },
  {
   "title": "fetcher batch run times",
   "type": "graph",
   "description": "max run time in milliseconds",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "stats.timers.mc.staging.story-indexer.fetcher.main_loop.upper"
    }
   ]
  },
  {
   "title": "Parser",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "stats.counters.mc.staging.story-indexer.parser.parsed-stories.*.count"
    }
   ]
  },
  {
   "title": "parser stories by Worker status (stacked)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "stats.timers.mc.staging.story-indexer.parser.message.*.count"
    }
   ]
  },
  {
   "title": "Importer",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "stats.counters.mc.staging.story-indexer.importer.imported-stories.*.count"
    }
   ]
  },
  {
   "title": "Importer stories by Worker status (stacked)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "stats.timers.mc.staging.story-indexer.importer.message.*.count"
    }
   ]
  },
  {
   "title": "Queues",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "stats.gauges.mc.staging.story-indexer.rabbitmq-stats.queues.ready.*"
    }
   ]
  }
 ]
}