{
 "title": "story-indexer (all realms)",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "realm",
    "query": "prod,hist-prod,csv-prod,rss-prod,arch-prod,staging,hist-staging,csv-staging,rss-staging,arch-staging,pbudne,pgulley,hist-pbudne,arch-pbudne,rss-pbudne,csv-xodhiambo,hist-xodhiambo,rss-xodhiambo"
   }
  ]
 },
 "panels": [
  {
   "title": "Queue messages ready",
   "type": "graph",
   "description": "in: ready for processing;\ndelay: 60 minute retry delay;\nquar: failed after multiple retries\nfast: delayed two minutes for fast retry",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasSub(aliasByNode(stats.gauges.mc.$realm.story-indexer.rabbitmq-stats.queues.ready.*, -1), 'name_(.*)', '\\1')"
    }
   ]
  },
  {
   "title": "messages sent per second",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasSub(aliasByNode(stats.counters.mc.$realm.story-indexer.*.sent-msgs.*.rate, 5, 7), '(.*).dest_(.*)', '\\1>\\2')"
    }
   ]
  },
  {
   "title": "app max run time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "target": "aliasByNode(stats.timers.mc.$realm.story-indexer.*.main_loop.upper, 5)"
    }
   ]
  },
  {
   "title": "worker containers running",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasSub(aliasSub(aliasByNode(stats.gauges.mc.$realm.story-indexer.docker-stats.service.running.*er, -1), '^name_(.*)', '\\1'), '(.*)-worker', '\\1')"
    }
   ]
  },
  {
   "title": "Queuer status (stories/second)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByNode(stats.counters.mc.$realm.story-indexer.*queuer.stories.*, -2)"
    },
    {
     "target": "aliasByNode(stats.counters.mc.$realm.story-indexer.*puller.stories.status_*.rate, -2)"
    }
   ]
  },
  {
   "title": "worker retry & quarantine counts",
   "type": "graph",
   "description": "retries and errors across all workers",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasSub(aliasByNode(stats.timers.mc.$realm.story-indexer.*.message.stat_{error,retry*}.count, 5, 7), '(.*).stat_(.*)', '\\1.\\2')"
    }
   ]
  },
  {
   "title": "Fetcher status (stories per second)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasSub(aliasByNode(stats.counters.mc.$realm.story-indexer.*fetcher.stories.*.rate, -2), 'status_(.*)', '\\1')"
    }
   ]
  },
  {
   "title": "mean parser metadata extract times",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "target": "aliasByNode(stats.timers.mc.$realm.story-indexer.parser.extract.*.mean, -2)"
    },
    {
     "target": "aliasByNode(stats.timers.mc.$realm.story-indexer.parser.encoding.mean, -2)"
    }
   ]
  },
  {
   "title": "Parser status (stories per second)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasSub(aliasByNode(stats.counters.mc.$realm.story-indexer.parser.stories.*.rate, -2), '^status_(.*)', '\\1')"
    }
   ]
  },
  {
   "title": "mean processing time per message",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "target": "aliasByNode(stats.timers.mc.$realm.story-indexer.*.message.stat_ok.mean, -4)"
    }
   ]
  },
  {
   "title": "Importer status (stories/second)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByNode(stats.counters.mc.$realm.story-indexer.importer.stories.*.rate, -2)"
    }
   ]
  },
  {
   "title": "Queue messages unacked",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 40 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByNode(stats.gauges.mc.$realm.story-indexer.rabbitmq-stats.queues.unacked.*-in, -1)"
    }
   ]
  },
  {
   "title": "Archiver file upload time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 48 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "target": "stats.timers.mc.$realm.story-indexer.archiver.upload.*.upper"
    }
   ]
  },
  {
   "title": "producer disk free check (only done if queue low)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 48 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "target": "stats.gauges.mc.$realm.story-indexer.*.data-disk-free"
    }
   ]
  },
  {
   "title": "pipeview crumb processing rate",
   "type": "graph",
   "description": "Shows where in the pipeline stories STOPPED being processed\n",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 56 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByNode(stats.counters.mc.$realm.story-indexer.pipeview.crumbs.*.rate, -2)"
    }
   ]
  },
  {
   "title": "producer check-output status",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 56 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByNode(stats.counters.mc.$realm.story-indexer.*.check-output.status*.count, -2)"
    }
   ]
  },
  {
   "title": "stories available from rss-fetcher",
   "type": "graph",
   "description": "Available rss-fetcher max-id is polled every five minutes\n",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 64 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "removeBelowValue(diffSeries(stats.gauges.mc.prod.rss-fetcher.rss-fetcher-stats.stories.max-id, stats.gauges.mc.$realm.story-indexer.rss-puller.stories.max-id), 0)"
    }
   ]
  },
  {
   "title": "Fetcher Messages (stacked)",
   "type": "graph",
   "description": "Totals of fetcher messages",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 64 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "refCount": -1,
     "target": "aliasSub(aliasByNode(stats.gauges.mc.$realm.story-indexer.rabbitmq-stats.queues.ready.name_fetcher-*, -1), 'name_(.*)', '\\1')"
    },
    {
     "refCount": -1,
     "target": "alias(stats.gauges.mc.$realm.story-indexer.rabbitmq-stats.queues.unacked.name_fetcher-in, 'fetcher-in.unacked')"
    },
    {
     "target": "alias(sumSeries(#A,#B),'total')",
     "targetFull": "alias(sumSeries(aliasSub(aliasByNode(stats.gauges.mc.$realm.story-indexer.rabbitmq-stats.queues.ready.name_fetcher-*, -1), 'name_(.*)', '\\1'),alias(stats.gauges.mc.$realm.story-indexer.rabbitmq-stats.queues.unacked.name_fetcher-in, 'fetcher-in.unacked')),'total')"
    }
   ]
  }
 ]
}