{
 "title": "story-indexer alerts",
 "time": { "from": "now-24h", "to": "now" },
 "panels": [
  {
   "title": "Production Stories Added to ES by hour",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "refCount": -1,
     "target": "summarize(stats.counters.mc.prod.story-indexer.importer.stories.status_created.count, '1h', 'sum', false)"
    }
   ]
  },
  {
   "title": "sum of all input & delay queues",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "sumSeries(stats.gauges.mc.prod.story-indexer.rabbitmq-stats.queues.ready.*-in, stats.gauges.mc.prod.story-indexer.rabbitmq-stats.queues.ready.*-delay, stats.gauges.mc.prod.story-indexer.rabbitmq-stats.queues.ready.*-fast)"
    }
   ]
  },
  {
   "title": "ES unhealthy indices",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "stats.gauges.mc.prod.story-indexer.elastic-stats.indices.health.color_red"
    },
    {
     "target": "stats.gauges.mc.prod.story-indexer.elastic-stats.indices.health.color_yellow"
    }
   ]
  },
  {
   "title": "Stories available from rss-fetcher",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "diffSeries(stats.gauges.mc.prod.rss-fetcher.rss-fetcher-stats.stories.max-id,stats.gauges.mc.prod.story-indexer.rss-puller.stories.max-id)"
    }
   ]
  },
  {
   "title": "Pending Tasks",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "stats.gauges.mc.prod.story-indexer.elastic-stats.cluster.health.pending_tasks.pending_tasks"
    }
   ]
  },
  {
   "title": "all prod quarantine queues",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "sumSeries(stats.gauges.mc.*prod.story-indexer.rabbitmq-stats.queues.ready.*-quar)"
    }
   ]
  },
  {
   "title": "Last Snapshot Success",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "stats.gauges.mc.prod.story-indexer.elastic-stats.snapshot.last.state_success"
    }
   ]
  },
  {
   "title": "Search API latency",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "target": "stats.timers.mc.prod.web-search.monitor-api.college.31d.count-over-time.median"
    }
   ]
  },
  {
   "title": "ES Server Load Average average",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 33 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "averageSeries(stats.gauges.mc.systems.load.15.es*)"
    }
   ]
  },
  {
   "title": "Time since last successful snapshot",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 33 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "target": "stats.gauges.mc.prod.story-indexer.elastic-stats.snapshot.time_since_last_start.state_success"
    }
   ]
  },
  {
   "title": "Importer input queue",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 41 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "stats.gauges.mc.prod.story-indexer.rabbitmq-stats.queues.ready.name_importer-in"
    }
   ]
  },
  {
   "title": "Total stories",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 41 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "sumSeries(stats.gauges.mc.prod.story-indexer.elastic-stats.indices.indices.primaries.docs.count.*)"
    }
   ]
  }
 ]
}