{
 "title": "story-indexer hist-prod",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "title": "Queues",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "stats.gauges.mc.hist-prod.story-indexer.rabbitmq-stats.queues.ready.name_*"
    }
   ]
  },
  {
   "title": "Message rates",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "stats.counters.mc.hist-prod.story-indexer.*.sent-msgs.*.rate"
    }
   ]
  },
  {
   "title": "Original fetch date/time seen by importer",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "dateTimeAsIso" }
   ],
   "targets": [
    {
     "target": "stats.timers.mc.hist-prod.story-indexer.importer.fetch-ts.upper"
    }
   ]
  },
  {
   "title": "Worker mean processing time (ms)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "stats.timers.mc.hist-prod.story-indexer.*.message.stat_ok.mean"
    }
   ]
  },
  {
   "title": "Importer status (stories/second)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "stats.counters.mc.hist-prod.story-indexer.importer.stories.*.rate"
    }
   ]
  },
  {
   "title": "Containers running",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "stats.gauges.mc.hist-prod.story-indexer.docker-stats.service.running.name_*"
    }
   ]
  }
 ]
}