{
 "title": "web-search stats",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "realm", "query": "prod,staging, pbudne, pgulley" }
  ]
 },
 "panels": [
  {
   "title": "monitor-api timings",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "target": "stats.timers.mc.$realm.web-search.monitor-api.*.*.*.median"
    }
   ]
  },
  {
   "title": "web-search API max times by app",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "target": "stats.timers.mc.$realm.web-search.api.success.*.upper"
    }
   ]
  },
  {
   "title": "web-search API calls/second",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "target": "stats.counters.mc.$realm.web-search.api.calls.*.status_*.rate"
    },
    {
     "target": "stats.counters.mc.$realm.web-search.api.calls.*.*.status_*.rate"
    },
    {
     "target": "stats.counters.mc.$realm.web-search.api.calls.*.*.*.status_*.rate"
    },
    {
     "target": "stats.counters.mc.$realm.web-search.api.calls.*.*.*.*.status_*.rate"
    }
   ]
  },
  {
   "title": "cache hits/misses",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "target": "stats.counters.mc.$realm.web-search.cache.total.*.count"
    }
   ]
  },
  {
   "title": "gunicorn request status",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "stats.counters.mc.$realm.web-search.gunicorn.request.status.*.count"
    }
   ]
  },
  {
   "title": "gunicorn workers",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "stats.gauges.mc.$realm.web-search.gunicorn.workers"
    }
   ]
  },
  {
   "title": "gunicorn request duration",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "target": "stats.timers.mc.$realm.web-search.gunicorn.request.duration.upper"
    },
    {
     "target": "stats.timers.mc.$realm.web-search.gunicorn.request.duration.mean"
    },
    {
     "target": "stats.timers.mc.$realm.web-search.gunicorn.request.duration.lower"
    },
    {
     "target": "stats.timers.mc.$realm.web-search.gunicorn.request.duration.std"
    }
   ]
  },
  {
   "title": "nginx",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "nonNegativeDerivative(stats.gauges.mc.nginx.*.total.*)"
    },
    {}
   ]
  },
  {
   "title": "nginx waiting",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "stats.gauges.mc.nginx.*.curr.waiting"
    },
    {}
   ]
  },
  {
   "title": "nginx writing",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "stats.gauges.mc.nginx.*.curr.writing"
    },
    {}
   ]
  },
  {
   "title": "Tasks Queued",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "stats.gauges.mc.$realm.web-search.tasks.waiting.*"
    }
   ]
  },
  {
   "title": "Tasks Completed",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 40 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "stats.gauges.mc.$realm.web-search.tasks.completed.*.*"
    }
   ]
  },
  {
   "title": "provider call rates",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 48 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "stats.counters.mc.$realm.web-search.provider.*.query.*.rate"
    }
   ]
  }
 ]
}